[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[window]
opacity = 0.8
decorations = "None"

[window.dimensions]
columns = 136
lines = 36
